# file: ansible-role-hobbes/tasks/main.yml

- name: HOBBES | check if already installed
  shell: command -v hi >/dev/null 2>&1
  register: hobbes_exists
  ignore_errors: yes

- debug: msg="{{ hobbes_exists.rc }}" # it returns rc 1
- debug: var=hobbes_exists

- name: HOBBES | get from git repository
  git: repo="{{ hobbes_repo_url }}"
       dest="{{ hobbes_tmp }}"
  when: not hobbes_exists.rc == 0
  register: hobbes_downloaded

# due to some bug in bison parser there is warning
# error: ‘void free(void*)’ called on unallocated object ‘yyssa’ [-Werror=free-nonheap-object]
# which gets truned into error
# this is false positive so disable
# see discussion at: https://lists.gnu.org/archive/html/help-bison/2021-01/msg00021.html
- name: HOBBES | Patch compile warning
  become: true
  replace:
      path="{{hobbes_tmp }}/{{ item }}"
      regexp='-Wall'
      replace='-Wall -Wno-free-nonheap-object '
      backup=no
  with_items:
  - CMakeLists.txt
  when: hobbes_patch_warning == True

- name: HOBBES | Make build folder
  become: true
  file: path="{{ hobbes_build_dir }}" state=directory
  when: hobbes_downloaded.changed

- name: HOBBES | cmake
  become: true
  command: chdir="{{ hobbes_build_dir }}" \
           cmake cmake -G "Unix Makefiles" "{{ hobbes_tmp }}" \
           -DCMAKE_INSTALL_PREFIX="{{ hobbes_install_dir }}" \
           -DPYTHON_EXECUTABLE="/usr/bin/python3" \
           "{{ hobbes_tmp }}"
  when: hobbes_downloaded.changed

- name: HOBBES | make
  become: true
  command: chdir="{{ hobbes_build_dir }}" make
  when: hobbes_downloaded.changed

- name: HOBBES | install
  become: true
  command: chdir="{{ hobbes_build_dir }}" make install
  when: hobbes_downloaded.changed

- name: HOBBES | cleanup build dir
  become: true
  file:
    path: "{{ hobbes_build_dir }}"
    state: absent
  when: hobbes_downloaded.changed

- name: HOBBES | cleanup tmp dir
  become: true
  file:
    path: "{{ hobbes_tmp }}"
    state: absent
  when: hobbes_downloaded.changed
